### ISSUE TITLE
create DAO (user)

### ISSUE THREAD

**Issue by drerek** [ydeineka/meetup#11]
Нужен метод findUserByUserName(String userName), findUserByMail(String mail), findUserById(String byUserId), ну либо похожие методы. 
При неудачном insertUser вернуть -1
при поиске вернуть либо сущность либо null если такого пользователя не было найдено.
Спасибо!

**Comment by svintsov** [comment]
интерфейс сделал. смотрите названия методов. они аналогичны, но отличаются названием

**Comment by drerek** [comment]
Спасибо, когда будешь делать реализацию зайди в ветку registration, там я покидал ссылки по поводу генерации первичного ключа...
