### ISSUE TITLE
Recovering password DAO

### ISSUE THREAD

**Issue by drerek** [ydeineka/meetup#12]
Ребят, пишу восстановление пароля, нужна dao на сущность Recover с полями     
private int id;
private String email;
private long expiredTime;
private String link;

И нужна доп таблица соответственно. 

Нужен метод findByEmail(String mail), если не найдено то null
findByLink(String link) если не найдено то null, и если можно то самую последнюю запись, если нет, то будем думать что-то по другому
insert(Recover recover), если не добавилось -1
delete, update, findById можно не реализовывать...

**Comment by Ppridorozhny** [comment]
может, лучше сгенерить фиктивный пароль, а потом его изменить в профиле, чтобы не создавать излишних сущностей?
