### ISSUE TITLE
fix showing of events and add filters

### ISSUE THREAD

**Issue by denysYashchuk** [ydeineka/meetup#51]
Showing categories
Open category -> list of events (table)
on event click - open event

**Comment by denysYashchuk** [comment]
Use one component for different categories

**Comment by Eugene1992** [comment]
Table should contain:
- pagination
- dropdown where i can choose number of showed items
- filters for all columns, which can be used like 'AND' operator
- pagination
Ideally i want to see something like that :)
![image](https://user-images.githubusercontent.com/11740952/39291679-79571b68-493c-11e8-9a3f-4f79c591201d.png)
