### ISSUE TITLE
Front-end polishing

### ISSUE THREAD

**Issue by denysYashchuk** [ydeineka/meetup#88]
Add scroll to participants
Update local storage on edit
Add checks to the phone number (full phone number only)

**Comment by Eugene1992** [comment]
> Use panels (optional)
Можно даже required сделать, иначе не придем к одному стилю)
На встрече я говорил о этих panel - https://www.w3schools.com/bootstrap/bootstrap_panels.asp

**Comment by Eugene1992** [comment]
И вообщем было бы неплохо все перевести на bootstrap компоненты, например кнопку изменения профайла на https://www.w3schools.com/bootstrap/bootstrap_buttons.asp 
+ разместить все более менее user firendly
